<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>explorer_state – iSamples</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./assets/isamplesfavicon.ico" rel="icon">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-84244d6014897f94eda7509784684fcb.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="./index.html" class="navbar-brand navbar-brand-logo">
    <img src="./assets/isampleslogopetal.png" alt="" class="navbar-logo light-content">
    <img src="./assets/isampleslogopetal.png" alt="" class="navbar-logo dark-content">
    </a>
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">iSamples</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./explorer.html"> 
<span class="menu-text">Interactive Explorer</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-how-to-use" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">How to Use</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-how-to-use">    
        <li>
    <a class="dropdown-item" href="./how-to-use.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./tutorials/zenodo_isamples_analysis.html">
 <span class="dropdown-text">Deep-Dive Analysis</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-about" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">About</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-about">    
        <li>
    <a class="dropdown-item" href="./about.html">
 <span class="dropdown-text">Objectives</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./about.html#team">
 <span class="dropdown-text">PIs and Contributors</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./about.html#photo-gallery">
 <span class="dropdown-text">Photo Gallery</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./about.html#background-history">
 <span class="dropdown-text">Background &amp; History</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-architecture--vocabularies" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Architecture &amp; Vocabularies</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-architecture--vocabularies">    
        <li>
    <a class="dropdown-item" href="./design/index.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./design/requirements.html">
 <span class="dropdown-text">Requirements</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://isamples.org/metadata/">
 <span class="dropdown-text">Metadata Model</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./models/index.html">
 <span class="dropdown-text">Vocabularies</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./tutorials/narrow_vs_wide_performance.html">
 <span class="dropdown-text">Technical: Narrow vs Wide</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./tutorials/why_h3.html">
 <span class="dropdown-text">Technical: Why H3?</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-research--resources" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Research &amp; Resources</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-research--resources">    
        <li>
    <a class="dropdown-item" href="./pubs.html">
 <span class="dropdown-text">Publications &amp; Conferences</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./pubs.html#zenodo-community">
 <span class="dropdown-text">Zenodo Community</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./pubs.html#github-repositories">
 <span class="dropdown-text">Github Repositories</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/isamplesorg"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://isamples.slack.com/"> <i class="bi bi-slack" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#explorer-state-contract" id="toc-explorer-state-contract" class="nav-link active" data-scroll-target="#explorer-state-contract"><span class="header-section-number">1</span> Explorer State Contract</a>
  <ul>
  <li><a href="#url-query-params-location.search" id="toc-url-query-params-location.search" class="nav-link" data-scroll-target="#url-query-params-location.search"><span class="header-section-number">1.1</span> 1. URL query params (<code>location.search</code>)</a>
  <ul class="collapse">
  <li><a href="#quarto-site-search-collision" id="toc-quarto-site-search-collision" class="nav-link" data-scroll-target="#quarto-site-search-collision"><span class="header-section-number">1.1.1</span> Quarto site-search collision</a></li>
  </ul></li>
  <li><a href="#url-hash-params-location.hash" id="toc-url-hash-params-location.hash" class="nav-link" data-scroll-target="#url-hash-params-location.hash"><span class="header-section-number">1.2</span> 2. URL hash params (<code>location.hash</code>)</a>
  <ul class="collapse">
  <li><a href="#hash-write-vs-read-coordination" id="toc-hash-write-vs-read-coordination" class="nav-link" data-scroll-target="#hash-write-vs-read-coordination"><span class="header-section-number">1.2.1</span> Hash write-vs-read coordination</a></li>
  <li><a href="#backforward-listener" id="toc-backforward-listener" class="nav-link" data-scroll-target="#backforward-listener"><span class="header-section-number">1.2.2</span> <code>back/forward</code> listener</a></li>
  </ul></li>
  <li><a href="#dom-as-state" id="toc-dom-as-state" class="nav-link" data-scroll-target="#dom-as-state"><span class="header-section-number">1.3</span> 3. DOM-as-state</a></li>
  <li><a href="#widget-internal-state-viewer.-window." id="toc-widget-internal-state-viewer.-window." class="nav-link" data-scroll-target="#widget-internal-state-viewer.-window."><span class="header-section-number">1.4</span> 4. Widget-internal state (<code>viewer.*</code> / <code>window.*</code>)</a>
  <ul class="collapse">
  <li><a href="#async-selection-invariant" id="toc-async-selection-invariant" class="nav-link" data-scroll-target="#async-selection-invariant"><span class="header-section-number">1.4.1</span> Async-selection invariant</a></li>
  <li><a href="#urlparamshydrated-confirmed-gone" id="toc-urlparamshydrated-confirmed-gone" class="nav-link" data-scroll-target="#urlparamshydrated-confirmed-gone"><span class="header-section-number">1.4.2</span> <code>_urlParamsHydrated</code> — confirmed gone</a></li>
  </ul></li>
  <li><a href="#ojs-cell-graph" id="toc-ojs-cell-graph" class="nav-link" data-scroll-target="#ojs-cell-graph"><span class="header-section-number">1.5</span> 5. OJS cell graph</a></li>
  <li><a href="#search-semantics-decision" id="toc-search-semantics-decision" class="nav-link" data-scroll-target="#search-semantics-decision"><span class="header-section-number">1.6</span> 6. Search-semantics decision</a>
  <ul class="collapse">
  <li><a href="#what-search-does-today-dosearch-at-1782-1859" id="toc-what-search-does-today-dosearch-at-1782-1859" class="nav-link" data-scroll-target="#what-search-does-today-dosearch-at-1782-1859"><span class="header-section-number">1.6.1</span> What “search” does today (<code>doSearch</code> at <code>:1782-1859</code>)</a></li>
  <li><a href="#the-three-options" id="toc-the-three-options" class="nav-link" data-scroll-target="#the-three-options"><span class="header-section-number">1.6.2</span> The three options</a></li>
  <li><a href="#decision-c-side-panel-lookup-with-result-pin-overlay" id="toc-decision-c-side-panel-lookup-with-result-pin-overlay" class="nav-link" data-scroll-target="#decision-c-side-panel-lookup-with-result-pin-overlay"><span class="header-section-number">1.6.3</span> Decision: (C) side-panel lookup with result-pin overlay</a></li>
  <li><a href="#implementation-rules-for-option-c" id="toc-implementation-rules-for-option-c" class="nav-link" data-scroll-target="#implementation-rules-for-option-c"><span class="header-section-number">1.6.4</span> Implementation rules for option (C)</a></li>
  <li><a href="#result-set-shape-acceptance-cases" id="toc-result-set-shape-acceptance-cases" class="nav-link" data-scroll-target="#result-set-shape-acceptance-cases"><span class="header-section-number">1.6.5</span> Result-set shape acceptance cases</a></li>
  <li><a href="#state-inventory-addendum-for-c" id="toc-state-inventory-addendum-for-c" class="nav-link" data-scroll-target="#state-inventory-addendum-for-c"><span class="header-section-number">1.6.6</span> State-inventory addendum for (C)</a></li>
  <li><a href="#light-path-addendum-two-button-scope-selection-178-2026-05-08" id="toc-light-path-addendum-two-button-scope-selection-178-2026-05-08" class="nav-link" data-scroll-target="#light-path-addendum-two-button-scope-selection-178-2026-05-08"><span class="header-section-number">1.6.7</span> Light-path addendum: two-button scope selection (#178, 2026-05-08)</a></li>
  <li><a href="#mockup-v1-addendum-in-map-overlay-sidebar-mirror-permanent-table-200-2026-05" id="toc-mockup-v1-addendum-in-map-overlay-sidebar-mirror-permanent-table-200-2026-05" class="nav-link" data-scroll-target="#mockup-v1-addendum-in-map-overlay-sidebar-mirror-permanent-table-200-2026-05"><span class="header-section-number">1.6.8</span> Mockup-v1 addendum: in-map overlay, sidebar mirror, permanent table (#200, 2026-05)</a></li>
  <li><a href="#table-v2-addendum-server-side-pagination-218-2026-05" id="toc-table-v2-addendum-server-side-pagination-218-2026-05" class="nav-link" data-scroll-target="#table-v2-addendum-server-side-pagination-218-2026-05"><span class="header-section-number">1.6.9</span> Table v2 addendum: server-side pagination (#218, 2026-05)</a></li>
  </ul></li>
  <li><a href="#facet-count-contract" id="toc-facet-count-contract" class="nav-link" data-scroll-target="#facet-count-contract"><span class="header-section-number">1.7</span> 7. Facet-count contract</a></li>
  <li><a href="#out-of-scope" id="toc-out-of-scope" class="nav-link" data-scroll-target="#out-of-scope"><span class="header-section-number">1.8</span> 8. Out of scope</a></li>
  <li><a href="#acceptance-signals" id="toc-acceptance-signals" class="nav-link" data-scroll-target="#acceptance-signals"><span class="header-section-number">1.9</span> 9. Acceptance signals</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/isamplesorg/isamplesorg.github.io/edit/main/EXPLORER_STATE.md" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/isamplesorg/isamplesorg.github.io/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"></header>




<section id="explorer-state-contract" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Explorer State Contract</h1>
<p>Doc-only contract for <code>explorer.qmd</code>. Locks down where every piece of explorer state lives, who owns it, when it gets written, and what the cross-filter rules are. Resolves <a href="https://github.com/isamplesorg/isamplesorg.github.io/issues/164">#164</a>; unblocks the items in <a href="https://github.com/isamplesorg/isamplesorg.github.io/issues/163">#163</a>.</p>
<p><strong>Direction</strong>: imperative + URL-as-canonical-state. OJS cells are used as a DAG-aware bootstrap (run viewer once, run phase1 after viewer is ready, etc.), not as a reactive UI runtime. All user-driven UI updates go through <code>writeQueryState()</code> → <code>history.replaceState</code> and direct DOM mutation. Reading DOM checkboxes is the source of truth for facet state inside SQL builders; the URL is the source of truth across reloads.</p>
<p>All file:line references below are against <code>explorer.qmd</code> at commit <code>94e7674</code> (the tree this doc was originally written against). The inventory has had targeted edits as later changes land — most notably the <strong>mockup-v1 PR</strong> (<a href="https://github.com/isamplesorg/isamplesorg.github.io/issues/200">#200</a>) which removed the Globe/Table view toggle, relocated search into an in-map overlay, added a sidebar search input that mirrors the in-map one, and made the samples table a permanent surface below the globe. See §6 “Mockup-v1 addendum” for the full delta. Line numbers may not match exactly; the contract is the source of truth, not the line citations.</p>
<hr>
<section id="url-query-params-location.search" class="level2" data-number="1.1">
<h2 data-number="1.1" data-anchor-id="url-query-params-location.search"><span class="header-section-number">1.1</span> 1. URL query params (<code>location.search</code>)</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 10%">
<col style="width: 11%">
<col style="width: 18%">
<col style="width: 22%">
<col style="width: 13%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th>field</th>
<th>owner</th>
<th>default</th>
<th>URL repr</th>
<th>hydration site</th>
<th>write-back trigger</th>
<th>validation</th>
<th>notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>search</code></td>
<td>DOM <code>#sampleSearch</code> value (mirrored to <code>#sampleSearchSidebar</code>)</td>
<td>omitted</td>
<td>raw string</td>
<td><code>applyQueryToSearch()</code> at start of <code>phase1</code> (hydrates both inputs)</td>
<td><code>writeQueryState()</code> called from <code>doSearch()</code></td>
<td>trim only; min 2 chars enforced at search time, not in URL</td>
<td>written even on no-result searches</td>
</tr>
<tr class="even">
<td><code>sources</code></td>
<td>DOM <code>#sourceFilter</code> checkboxes</td>
<td>omitted (= all 4 checked)</td>
<td>CSV of <code>SOURCE_VALUES</code> ∩ user-checked</td>
<td><code>applyQueryToSourceFilter()</code> at start of <code>phase1</code> (<code>:938</code>)</td>
<td><code>writeQueryState()</code> from source filter <code>change</code> (<code>:1620</code>)</td>
<td>filtered by <code>SOURCE_VALUES</code> allowlist (<code>:407</code>); param removed when all 4 checked (<code>:449</code>)</td>
<td>empty (zero checked) renders as <code>&amp;sources=</code> and yields <code>1=0</code> predicate (<code>:379</code>)</td>
</tr>
<tr class="odd">
<td><code>material</code></td>
<td>DOM <code>#materialFilterBody</code> checkboxes</td>
<td>omitted (= no filter)</td>
<td>CSV of full URIs</td>
<td><code>applyQueryToFacetFilters()</code> at end of <code>facetFilters</code> (<code>:1061</code>)</td>
<td><code>writeQueryState()</code> from <code>handleFacetFilterChange</code> (<code>:1642</code>)</td>
<td>none — checkbox <code>value</code> already constrained by render</td>
<td>empty checked set ⇒ param removed (<code>:459</code>)</td>
</tr>
<tr class="even">
<td><code>context</code></td>
<td>DOM <code>#contextFilterBody</code> checkboxes</td>
<td>omitted</td>
<td>CSV of full URIs</td>
<td>same as <code>material</code></td>
<td>same as <code>material</code></td>
<td>none</td>
<td>same</td>
</tr>
<tr class="odd">
<td><code>object_type</code></td>
<td>DOM <code>#objectTypeFilterBody</code> checkboxes</td>
<td>omitted</td>
<td>CSV of full URIs</td>
<td>same as <code>material</code></td>
<td>same as <code>material</code></td>
<td>none</td>
<td>same</td>
</tr>
<tr class="even">
<td><del><code>view</code></del></td>
<td><em>removed in mockup-v1 (#200)</em></td>
<td>—</td>
<td>—</td>
<td>—</td>
<td>—</td>
<td>—</td>
<td>The Globe/Table toggle is gone — the samples table is now permanent below the globe. <code>writeQueryState()</code> does <code>params.delete('view')</code> to canonicalize legacy bookmarks. See §6 “Mockup-v1 addendum”</td>
</tr>
<tr class="odd">
<td><code>search_scope</code></td>
<td>local closure <code>_searchScope</code> in <code>zoomWatcher</code></td>
<td>omitted (= <code>world</code>)</td>
<td><code>area</code> only; absent ⇒ world</td>
<td><code>_searchScope</code> hydrated at top of <code>zoomWatcher</code> from <code>params.get('search_scope')</code></td>
<td><code>persistSearchScope()</code> from <code>doSearch()</code> and button clicks</td>
<td>exact match <code>'area'</code></td>
<td>sidebar <code>#sampleSearchSidebar</code> Enter always submits <code>world</code>, never <code>area</code> — see §6 mockup-v1 addendum</td>
</tr>
<tr class="even">
<td><code>page</code></td>
<td>inner closure <code>let page = 0</code> in <code>tableView</code></td>
<td>not in URL</td>
<td>—</td>
<td>—</td>
<td>resets to 0 on <code>refreshTable()</code>; ±1 on prev/next</td>
<td>clamped to <code>[0, totalPages-1]</code></td>
<td><strong>#163 item 6</strong> — table page is intentionally not URL state today; if/when added, must coexist with the cross-filter contract below</td>
</tr>
<tr class="odd">
<td><code>perf</code></td>
<td>— (read-only feature flag)</td>
<td>omitted</td>
<td><code>1</code> to enable</td>
<td><code>perfPanel</code> cell reads (<code>:1921-1922</code>)</td>
<td>never written</td>
<td><code>=== '1'</code> exact match</td>
<td>never round-tripped; safe to add other tail params</td>
</tr>
</tbody>
</table>
<section id="quarto-site-search-collision" class="level3" data-number="1.1.1">
<h3 data-number="1.1.1" data-anchor-id="quarto-site-search-collision"><span class="header-section-number">1.1.1</span> Quarto site-search collision</h3>
<p><code>?q=</code> is hijacked by Quarto’s site-wide search and stripped via <code>replaceState</code> (see comment at <code>:414-416</code>). That is why the explorer uses <code>?search=</code> for the sample text query. Don’t migrate to <code>q</code>.</p>
<hr>
</section>
</section>
<section id="url-hash-params-location.hash" class="level2" data-number="1.2">
<h2 data-number="1.2" data-anchor-id="url-hash-params-location.hash"><span class="header-section-number">1.2</span> 2. URL hash params (<code>location.hash</code>)</h2>
<p>The hash is the camera/deep-link channel. Always written together by <code>buildHash(viewer)</code> (<code>:597-613</code>), always read together by <code>readHash()</code> (<code>:583-595</code>).</p>
<table class="caption-top table">
<colgroup>
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 10%">
<col style="width: 12%">
<col style="width: 17%">
<col style="width: 22%">
<col style="width: 13%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th>field</th>
<th>owner</th>
<th>default</th>
<th>hash repr</th>
<th>hydration site</th>
<th>write-back trigger</th>
<th>validation</th>
<th>notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>v</code></td>
<td>constant</td>
<td><code>'1'</code> (always written)</td>
<td><code>v=1</code></td>
<td><code>readHash()</code> returns <code>parseInt() || 0</code> (<code>:586</code>)</td>
<td><code>buildHash</code> always sets <code>'1'</code> (<code>:601</code>)</td>
<td><code>parseInt</code>; non-numeric ⇒ 0</td>
<td>reserved for future schema bump</td>
</tr>
<tr class="even">
<td><code>lat</code></td>
<td><code>viewer.camera.positionCartographic</code></td>
<td>absent</td>
<td>4-decimal degrees</td>
<td><code>readHash()</code> (<code>:587</code>); applied in viewer <code>once</code> postRender (<code>:797-812</code>)</td>
<td>camera-change debounced 600ms (<code>:1700-1702</code>, <code>replaceState</code>); enter/exit point mode (<code>:1463</code>, <code>:1474</code>, <code>pushState</code>); sample/cluster click (<code>:861</code>, <code>:888</code>, <code>pushState</code>); share button (<code>:1763</code>, <code>replaceState</code>)</td>
<td>clamped <code>[-90, 90]</code> (<code>:587</code>)</td>
<td>written together with <code>lng</code>, <code>alt</code></td>
</tr>
<tr class="odd">
<td><code>lng</code></td>
<td>same</td>
<td>absent</td>
<td>4-decimal degrees</td>
<td>same</td>
<td>same</td>
<td>clamped <code>[-180, 180]</code> (<code>:588</code>)</td>
<td></td>
</tr>
<tr class="even">
<td><code>alt</code></td>
<td>same</td>
<td><code>null</code> ⇒ falls back to <code>20000000</code> (<code>:801</code>)</td>
<td>integer meters</td>
<td>same</td>
<td>same</td>
<td>clamped <code>[100, 40_000_000]</code> (<code>:589</code>)</td>
<td></td>
</tr>
<tr class="odd">
<td><code>heading</code></td>
<td><code>viewer.camera.heading</code></td>
<td><code>0</code></td>
<td>degrees, 1-decimal</td>
<td>same</td>
<td>same; only written if <code>\|heading\| &gt; 1</code> (<code>:607</code>)</td>
<td>clamped <code>[0, 360]</code> (<code>:590</code>)</td>
<td></td>
</tr>
<tr class="even">
<td><code>pitch</code></td>
<td><code>viewer.camera.pitch</code></td>
<td><code>-90</code></td>
<td>degrees, 1-decimal</td>
<td>same</td>
<td>same; only written if <code>\|pitch + 90\| &gt; 1</code> (<code>:608</code>)</td>
<td>clamped <code>[-90, 0]</code> (<code>:591</code>)</td>
<td></td>
</tr>
<tr class="odd">
<td><code>mode</code></td>
<td><code>viewer._globeState.mode</code></td>
<td>omitted (= <code>cluster</code>)</td>
<td><code>point</code> only</td>
<td><code>readHash()</code> (<code>:592</code>); applied after camera flight in <code>hashchange</code> handler (<code>:1727-1729</code>); also restored from <code>_initialHash</code> after zoomWatcher init</td>
<td><code>buildHash</code> only writes if <code>'point'</code> (<code>:610</code>); push triggers as above</td>
<td>exact-match <code>'point'</code></td>
<td>absence ⇒ cluster</td>
</tr>
<tr class="even">
<td><code>pid</code></td>
<td><code>viewer._globeState.selectedPid</code></td>
<td>omitted</td>
<td>sample pid string (URL-encoded)</td>
<td><code>readHash()</code> (<code>:593</code>); applied at end of <code>zoomWatcher</code> (<code>:1873-1901</code>) and on <code>hashchange</code> (<code>:1733-1756</code>)</td>
<td>sample-click sets it (<code>:860</code>); cluster-click clears it (<code>:887</code>); written in <code>buildHash</code> if non-null (<code>:611</code>)</td>
<td>none beyond <code>null</code> check</td>
<td>drives a <code>lite_url</code> lookup + lazy <code>wide_url</code> description fetch</td>
</tr>
<tr class="odd">
<td><code>h3</code></td>
<td><code>viewer._globeState.selectedH3</code></td>
<td>omitted</td>
<td>canonical 15-char lowercase hex (e.g.&nbsp;<code>843f6d3ffffffff</code>)</td>
<td><code>readHash()</code> parses; boot deep-link calls <code>fetchClusterByH3</code> then <code>hydrateClusterUI</code> under a <code>_selGen</code> race guard; same path on <code>hashchange</code></td>
<td>cluster-click sets <code>selectedH3 = meta.h3_cell</code> and clears <code>selectedPid</code> (mutual exclusion); sample-click clears <code>selectedH3</code>; source-filter change re-validates and may clear or rehydrate; written in <code>buildHash</code> if non-null</td>
<td>strict <code>/^[0-9a-f]{15}$/i</code>; cell-mode (<code>lower[0] === '8'</code>); resolution nibble in <code>RES_TO_H3_URL</code> map (4/6/8)</td>
<td>drives a single <code>WHERE h3_cell = CAST('&lt;decimal&gt;' AS UBIGINT) AND &lt;sourceFilterSQL&gt;</code> lookup against the resolution-routed parquet. h3_cell column is UBIGINT so SELECTs cast to VARCHAR and JS converts via <code>BigInt(dec).toString(16)</code> to avoid Number precision loss. <code>&amp;pid=</code> wins if both present. Per <code>EXPLORER_CLUSTER_URL_PROPOSAL.md</code></td>
</tr>
</tbody>
</table>
<section id="hash-write-vs-read-coordination" class="level3" data-number="1.2.1">
<h3 data-number="1.2.1" data-anchor-id="hash-write-vs-read-coordination"><span class="header-section-number">1.2.1</span> Hash write-vs-read coordination</h3>
<p><code>viewer._suppressHashWrite</code> (boot at <code>true</code> at <code>:791</code>, cleared at <code>:1904</code>) prevents the camera-change handler from rewriting the hash while the <code>hashchange</code> handler is mid-flight. The <code>_suppressTimer</code> (<code>:792</code>, <code>:1725</code>) re-arms after a 2-second flight settles. <strong>Do not remove this flag</strong> without re-deriving the camera→hash→camera echo prevention.</p>
</section>
<section id="backforward-listener" class="level3" data-number="1.2.2">
<h3 data-number="1.2.2" data-anchor-id="backforward-listener"><span class="header-section-number">1.2.2</span> <code>back/forward</code> listener</h3>
<p><code>window.addEventListener('hashchange', ...)</code> at <code>:1708</code> does the inverse of <code>buildHash</code>: flies the camera, restores the selected pid, and toggles <code>enterPointMode(false)</code> / <code>exitPointMode(false)</code> (the <code>false</code> suppresses a nested <code>pushState</code>).</p>
<hr>
</section>
</section>
<section id="dom-as-state" class="level2" data-number="1.3">
<h2 data-number="1.3" data-anchor-id="dom-as-state"><span class="header-section-number">1.3</span> 3. DOM-as-state</h2>
<p>State that lives only on the page tree. Authoritative because some of it predates the store-on-<code>viewer</code> pattern and isn’t worth migrating.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 22%">
<col style="width: 13%">
<col style="width: 27%">
<col style="width: 20%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th>location</th>
<th>role</th>
<th>written by</th>
<th>read by</th>
<th>notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><del><code>document.body.classList['table-view-active']</code></del></td>
<td><em>removed in mockup-v1 (#200)</em></td>
<td>—</td>
<td>—</td>
<td>The view marker class is gone with the Globe/Table toggle. The samples table is permanent below the globe; <code>isTableViewActive()</code> and <code>setView()</code> were deleted</td>
</tr>
<tr class="even">
<td><code>data-facet</code>, <code>data-value</code> on <code>.facet-row</code> and <code>.facet-count</code></td>
<td>facet selectors for in-place count mutation</td>
<td>rendered in <code>renderFilter</code> and the static source legend</td>
<td><code>applyFacetCounts()</code></td>
<td>rebuilding the HTML would lose mid-interaction selections; <code>data-*</code> attrs are why we mutate counts in place</td>
</tr>
<tr class="odd">
<td><code>data-lat</code>, <code>data-lng</code>, <code>data-pid</code> on <code>.sample-row</code></td>
<td>click-to-fly payload for search/nearby results</td>
<td>rendered in <code>doSearch()</code></td>
<td>search-row click handler</td>
<td>the nearby-samples list does not have data-* today; click-to-fly only works from the search list</td>
</tr>
<tr class="even">
<td><code>data-pid</code> on <code>.samples-table tbody tr</code></td>
<td>click-to-select payload for the permanent table</td>
<td>rendered in <code>tableView</code> <code>renderTable()</code></td>
<td>table-row click handler (same ceremony as the search-row click — see §6 mockup-v1 addendum)</td>
<td>per-PID lookup uses <code>pageRowsByPid: Map</code> cached per page at <code>loadPage()</code> time (table v2); only the current page is in memory</td>
</tr>
<tr class="odd">
<td><code>tr.selected</code> on <code>.samples-table</code></td>
<td>“this row is the current sample selection” visual marker</td>
<td>table-row click handler (<code>add</code>); next click on a different row (<code>remove</code>); next <code>renderTable()</code> reflects current <code>viewer._globeState.selectedPid</code></td>
<td>CSS only</td>
<td>derived; do not read. The globe → table direction is <em>not</em> live (only repaints on the next page load)</td>
</tr>
<tr class="even">
<td><code>#tableContainer.is-loading</code> + <code>aria-busy="true"</code></td>
<td>“table query in flight” marker</td>
<td><code>setLoading(true/false)</code> in <code>tableView</code> (table v2)</td>
<td>CSS dim (<code>.samples-table</code> opacity 0.6); screen readers</td>
<td>added in table v2 follow-up to PR #200 for stale-while-loading UX</td>
</tr>
<tr class="odd">
<td><code>.recomputing</code> on <code>.facet-count</code></td>
<td>transient “loading” styling during cross-filter recompute</td>
<td><code>markFacetCountsRecomputing()</code> (<code>:570</code>)</td>
<td><code>applyFacetCounts()</code> clears it (<code>:562</code>)</td>
<td>UI-only; not state in the persistence sense</td>
</tr>
<tr class="even">
<td><code>.zero</code> on <code>.facet-row</code></td>
<td>“value has zero count under current filters” styling</td>
<td><code>applyFacetCounts()</code> (<code>:565</code>)</td>
<td>CSS only</td>
<td>derived; do not read</td>
</tr>
<tr class="odd">
<td><code>.disabled</code> on <code>#sourceFilter .legend-item</code></td>
<td>unchecked source visual</td>
<td><code>updateSourceLegendState()</code> (<code>:395-400</code>)</td>
<td>CSS only</td>
<td>derived from checkbox <code>checked</code>; do not read</td>
</tr>
</tbody>
</table>
<p>DOM input elements (the four facet checkbox bodies + <code>#sampleSearch</code> + <code>#sampleSearchSidebar</code>) are the <strong>source of truth</strong> for <code>getActiveSources()</code>, <code>getCheckedValues()</code>, and the search input. SQL builders read <code>#sampleSearch</code> directly each call. <code>#sampleSearchSidebar</code> is kept in lock-step with <code>#sampleSearch</code> via a two-way <code>input</code>-event mirror (see §6 mockup-v1 addendum). The <code>#maxSamples</code> input and the <code>getTableMaxSamples()</code> / <code>clampTableMaxSamples()</code> helpers were removed in the table v2 follow-up — the samples table now paginates server-side via DuckDB <code>LIMIT/OFFSET</code> instead of fetching up to 25K rows up-front.</p>
<hr>
</section>
<section id="widget-internal-state-viewer.-window." class="level2" data-number="1.4">
<h2 data-number="1.4" data-anchor-id="widget-internal-state-viewer.-window."><span class="header-section-number">1.4</span> 4. Widget-internal state (<code>viewer.*</code> / <code>window.*</code>)</h2>
<p>Set on the Cesium <code>Viewer</code> instance during the <code>viewer</code> cell so it survives across cells without becoming a separate OJS reactive value.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 19%">
<col style="width: 16%">
<col style="width: 22%">
<col style="width: 25%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>field</th>
<th>type</th>
<th>set at</th>
<th>read at</th>
<th>role</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>viewer._globeState</code></td>
<td><code>{ mode: 'cluster'|'point', selectedPid: string|null }</code></td>
<td>init <code>:789</code>; mutated <code>:860, :887, :1460, :1470, :1734, :1754, :1875</code></td>
<td><code>buildHash</code> (<code>:609-611</code>)</td>
<td>authoritative client-side mode + selection; the URL hash is its serialization</td>
</tr>
<tr class="even">
<td><code>viewer._initialHash</code></td>
<td><code>readHash()</code> snapshot</td>
<td>init <code>:790</code></td>
<td>viewer first-frame <code>once</code> (<code>:797</code>); zoomWatcher boot deep-link (<code>:1873</code>)</td>
<td>preserves boot-time hash for late hydration</td>
</tr>
<tr class="odd">
<td><code>viewer._suppressHashWrite</code></td>
<td>bool</td>
<td>init <code>true</code> <code>:791</code>; cleared <code>:1904</code>; re-set/cleared in <code>hashchange</code> (<code>:1712</code>, <code>:1725</code>)</td>
<td>camera-change handler (<code>:1700</code>)</td>
<td>echo-loop guard</td>
</tr>
<tr class="even">
<td><code>viewer._suppressTimer</code></td>
<td>timer handle</td>
<td><code>:792</code>, <code>:1713</code>, <code>:1725</code></td>
<td>cleared in <code>:1713</code></td>
<td>re-arms <code>_suppressHashWrite</code> after camera flight</td>
</tr>
<tr class="odd">
<td><code>viewer._clusterData</code></td>
<td><code>Array&lt;row&gt;</code></td>
<td><code>:964</code> (phase1), <code>:1305</code> (loadRes)</td>
<td><code>countInViewport</code> (<code>:1342</code>); zoom recompute (<code>:1690</code>)</td>
<td>viewport count cache</td>
</tr>
<tr class="even">
<td><code>viewer._clusterTotal</code></td>
<td><code>{ clusters, samples }</code></td>
<td><code>:965</code>, <code>:1306</code></td>
<td>exitPointMode (<code>:1481</code>); zoom recompute (<code>:1693</code>)</td>
<td>totals for the “in view / loaded” stat</td>
</tr>
<tr class="odd">
<td><code>viewer._baselineCounts</code></td>
<td><code>{ source: Map, material: Map, context: Map, object_type: Map }</code></td>
<td><code>:1030-1035</code></td>
<td><code>applyFacetCounts()</code> (<code>:552</code>)</td>
<td>unfiltered facet counts; rendered when no cross-filter is active</td>
</tr>
<tr class="even">
<td><code>viewer.h3Points</code></td>
<td>Cesium <code>PointPrimitiveCollection</code></td>
<td><code>:815</code></td>
<td>cluster mode rendering</td>
<td></td>
</tr>
<tr class="odd">
<td><code>viewer.samplePoints</code></td>
<td>Cesium <code>PointPrimitiveCollection</code></td>
<td><code>:818</code></td>
<td>point mode rendering</td>
<td></td>
</tr>
<tr class="even">
<td><code>viewer.pointLabel</code></td>
<td>Cesium label entity</td>
<td><code>:823</code></td>
<td>mouse-move handler (<code>:836-848</code>)</td>
<td>hover tooltip</td>
</tr>
<tr class="odd">
<td><code>viewer._selGen</code></td>
<td>int</td>
<td>bumped by every <code>freshSelectionToken(viewer)</code> call (top-level helper, see invariant below)</td>
<td>snapshot captured by each handler that mutates selection</td>
<td>freshness counter; see invariant below</td>
</tr>
<tr class="even">
<td><code>window.refreshSamplesTable</code></td>
<td><code>() =&gt; Promise&lt;void&gt;</code></td>
<td><code>:1238</code></td>
<td>external (debug / Playwright)</td>
<td>not used by other cells; safe to keep or remove</td>
</tr>
</tbody>
</table>
<section id="async-selection-invariant" class="level3" data-number="1.4.1">
<h3 data-number="1.4.1" data-anchor-id="async-selection-invariant"><span class="header-section-number">1.4.1</span> Async-selection invariant</h3>
<p>Any async work that updates <code>viewer._globeState</code>, the URL hash, or the side-panel DOM <strong>must check freshness after every await</strong>. The <code>freshSelectionToken(viewer)</code> helper (defined at top level alongside <code>readHash</code> / <code>buildHash</code> so both the viewer-cell click handler and the zoomWatcher-cell handlers can reach it) is the primitive: each user-input event handler that touches selection (cluster/sample click, hashchange, source-filter toggle, boot deep-link) calls it once at start to bump <code>_selGen</code> and capture an <code>isStale()</code> closure; every subsequent await is followed by <code>if (isStale()) return;</code> before any state/URL/DOM mutation. Pass <code>isStale</code> into nested helpers (<code>hydrateClusterUI</code>’s second param) so their internal awaits also bail before touching the DOM.</p>
<p>This invariant exists because there’s no central “selection store” — selection state lives in <code>_globeState</code>, the URL hash, and the side-panel DOM, and four different paths (click, hashchange, filter, boot) write to all three. Without the freshness check, a slow earlier handler can repaint the side panel for a selection the user has already moved off of. Issue #187 has the post-mortem on the 6-round Codex review that motivated extracting the primitive.</p>
</section>
<section id="urlparamshydrated-confirmed-gone" class="level3" data-number="1.4.2">
<h3 data-number="1.4.2" data-anchor-id="urlparamshydrated-confirmed-gone"><span class="header-section-number">1.4.2</span> <code>_urlParamsHydrated</code> — confirmed gone</h3>
<p>Grep for <code>_urlParamsHydrated</code> in <code>explorer.qmd</code> returns no hits. The flag from PR #159’s first cut was removed; the new contract is “URL → DOM hydration runs exactly once per cell that owns the corresponding DOM, gated only by the OJS DAG (phase1 ⇒ source/search hydration; facetFilters ⇒ facet hydration). Mockup-v1 removed the <code>tableView ⇒ view</code> hydration step along with the <code>?view=</code> URL param.”</p>
<hr>
</section>
</section>
<section id="ojs-cell-graph" class="level2" data-number="1.5">
<h2 data-number="1.5" data-anchor-id="ojs-cell-graph"><span class="header-section-number">1.5</span> 5. OJS cell graph</h2>
<p>Document order, with declared dependencies and side effects. The cells form a fan-out from <code>viewer</code> + <code>db</code>:</p>
<pre><code>Cesium-token    [pure global mutation]
constants/helpers  [pure; defines URLs, palettes, ~40 helper functions]
db                 [DuckDBClient.of()]
viewer             [creates Cesium viewer; reads readHash() once]
  └── phase1       [needs viewer + db; runs URL→DOM hydration for search + sources]
        └── facetFilters    [needs phase1; loads vocab + summaries; sets _baselineCounts; runs URL→DOM hydration for facet checkboxes]
              ├── tableView    [needs facetFilters; calls refreshTable() unconditionally on boot — no URL hydration]
              └── zoomWatcher  [needs facetFilters; registers ALL change handlers; runs deep-link pid restore]
                    └── perfPanel  [opt-in; needs phase1; renders perf panel if ?perf=1]</code></pre>
<table class="caption-top table">
<colgroup>
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 19%">
<col style="width: 17%">
<col style="width: 34%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>cell</th>
<th>line</th>
<th>implicit deps</th>
<th>DOM mutation</th>
<th>event listeners registered</th>
<th>URL writes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Cesium token</td>
<td><code>:328</code></td>
<td>—</td>
<td>—</td>
<td>—</td>
<td>—</td>
</tr>
<tr class="even">
<td>constants/helpers</td>
<td><code>:333</code></td>
<td>—</td>
<td>—</td>
<td>—</td>
<td>—</td>
</tr>
<tr class="odd">
<td><code>db</code></td>
<td><code>:759</code></td>
<td>—</td>
<td>—</td>
<td>—</td>
<td>—</td>
</tr>
<tr class="even">
<td><code>viewer</code></td>
<td><code>:773</code></td>
<td>—</td>
<td><code>#cesiumContainer</code> mounts globe</td>
<td><code>scene.postRender</code>×2; mouse-move; left-click</td>
<td><code>pushState</code> (sample/cluster click)</td>
</tr>
<tr class="odd">
<td><code>phase1</code></td>
<td><code>:930</code></td>
<td><code>viewer</code>, <code>db</code></td>
<td><code>#sourceFilter</code> (via hydration); stats DOM</td>
<td>—</td>
<td>—</td>
</tr>
<tr class="even">
<td><code>facetFilters</code></td>
<td><code>:979</code></td>
<td><code>phase1</code>, <code>db</code></td>
<td><code>#materialFilterBody</code>, <code>#contextFilterBody</code>, <code>#objectTypeFilterBody</code>; facet count text</td>
<td>—</td>
<td>—</td>
</tr>
<tr class="odd">
<td><code>tableView</code></td>
<td><code>:1071</code></td>
<td><code>facetFilters</code></td>
<td><code>#tableContainer</code>, <code>#samplesTable</code>, <code>tr.selected</code> class</td>
<td>prev/next; max input; <strong>change</strong> on all four facet bodies; table-row clicks</td>
<td><code>replaceState</code> via <code>buildHash</code> from table-row click (sets <code>#pid</code> directly, mirrors sample-mode globe click)</td>
</tr>
<tr class="even">
<td><code>zoomWatcher</code></td>
<td><code>:1246</code></td>
<td><code>phase1</code>, <code>facetFilters</code>, <code>db</code></td>
<td>facet count text; stats; phase msg; sample card; samples list</td>
<td>source filter <code>change</code>; material/context/object_type <code>change</code>; <code>camera.changed</code>; <code>camera.moveEnd</code> (sub-threshold pan settle, #205); <code>window</code> <code>hashchange</code>; share button; search button; in-map search input keydown; sidebar search input <code>input</code> (mirror) and keydown (world-scope submit)</td>
<td><code>pushState</code> and <code>replaceState</code> via <code>buildHash</code> (camera changed/moveEnd, mode flip, sample fly, <strong>share button</strong>); <code>replaceState</code> via <code>writeQueryState</code> (filter changes, search submit)</td>
</tr>
<tr class="odd">
<td><code>tableView</code> (post table-v2 viewport coupling)</td>
<td>—</td>
<td><code>facetFilters</code>, <code>viewer</code></td>
<td>also listens to <code>viewer.camera.moveEnd</code> to re-scope table to viewport bbox</td>
<td>—</td>
<td>—</td>
</tr>
<tr class="even">
<td><code>perfPanel</code></td>
<td><code>:1910</code></td>
<td><code>phase1</code></td>
<td><code>#perfPanel</code> floating div</td>
<td>close button</td>
<td>—</td>
</tr>
</tbody>
</table>
<p>Note that <strong>two cells register <code>change</code> listeners on the four facet container elements</strong>: <code>tableView</code> calls <code>refreshTable()</code> unconditionally (the table is permanent post-mockup-v1, so there’s no view gate); <code>zoomWatcher</code> reloads the globe and debounces the cross-filter count refresh. Both listeners fire on every facet change; this is intentional (each cell handles its own concerns) but is the single most “magical” coupling in the file — touch with care.</p>
<hr>
</section>
<section id="search-semantics-decision" class="level2" data-number="1.6">
<h2 data-number="1.6" data-anchor-id="search-semantics-decision"><span class="header-section-number">1.6</span> 6. Search-semantics decision</h2>
<p>The issue originally presented two options (A) global filter and (B) side-panel lookup. After Codex review on #165, we committed to a sharper third framing: <strong>(C) side-panel lookup with result-pin overlay</strong>, which is a refinement of (B) — the <em>backend</em> is unchanged (search does not alter cluster/sample/facet data sources), but the <em>UI surface</em> gains a temporary point-overlay visualization of the matching samples.</p>
<section id="what-search-does-today-dosearch-at-1782-1859" class="level3" data-number="1.6.1">
<h3 data-number="1.6.1" data-anchor-id="what-search-does-today-dosearch-at-1782-1859"><span class="header-section-number">1.6.1</span> What “search” does today (<code>doSearch</code> at <code>:1782-1859</code>)</h3>
<p>Reads <code>#sampleSearch.value</code>. Runs an ILIKE-based DuckDB query against <code>lite_url</code> over <code>label</code> and <code>place_name</code>, with <code>sourceFilterSQL()</code> and <code>facetFilterSQL()</code> AND’d in. Renders up to 50 ranked results into <code>#searchResults</code> (count) and <code>#samplesSection</code> (list). Click a result row to fly the camera. <strong>The map clusters/samples are not filtered by the search text. Facet counts are not filtered by the search text.</strong> The URL <code>search</code> param is written via <code>writeQueryState()</code> (<code>:1786</code>, <code>:1789</code>).</p>
<p>That is option (B) verbatim, and it matches the facet-count fix Codex landed in <a href="https://github.com/isamplesorg/isamplesorg.github.io/pull/158">#158</a>.</p>
</section>
<section id="the-three-options" class="level3" data-number="1.6.2">
<h3 data-number="1.6.2" data-anchor-id="the-three-options"><span class="header-section-number">1.6.2</span> The three options</h3>
<ul>
<li><strong>(A) Global filter.</strong> Active search restricts the map layer, table, and facet counts to the matching subset. Forces cluster mode to drop to point mode whenever a search is active (H3 summaries are not text-indexable). Couples search semantics to camera/mode state. <strong>Rejected.</strong></li>
<li><strong>(B) Side-panel lookup.</strong> Search populates the side panel only; map + facet counts ignore it. Today’s behavior. Leaves <a href="https://github.com/isamplesorg/isamplesorg.github.io/issues/163">#163 item 4</a> as a UX wart (zero results + populated map). <strong>Insufficient.</strong></li>
<li><strong>(C) Side-panel lookup with result-pin overlay.</strong> Search populates the side panel <strong>and</strong> renders a temporary point-overlay of the matching samples on the globe — independent of the H3 cluster layer and the facet counts. The cluster layer remains accurate (no facet-aware text indexing required); the overlay visualizes “your search matched these samples, here are their locations.” Cleared when the user clears the search. <strong>Adopted.</strong></li>
</ul>
</section>
<section id="decision-c-side-panel-lookup-with-result-pin-overlay" class="level3" data-number="1.6.3">
<h3 data-number="1.6.3" data-anchor-id="decision-c-side-panel-lookup-with-result-pin-overlay"><span class="header-section-number">1.6.3</span> Decision: (C) side-panel lookup with result-pin overlay</h3>
<p><strong>What stays the same as (B).</strong> The backend / data-source contract is unchanged from option (B):</p>
<ol type="1">
<li>The H3 summary parquets carry only <code>dominant_source</code>, <code>sample_count</code>, and centroid coords. Cluster mode is <strong>not</strong> text-aware.</li>
<li>The cross-filter facet-count contract landed in #158 still excludes search from the count predicate.</li>
<li><code>viewer._globeState</code> does not gain a search-active mode; the cluster primitive collection is unaffected.</li>
</ol>
<p><strong>What’s new in (C).</strong> A <em>third</em> primitive collection on the viewer: <code>viewer.searchResultPoints</code> (Cesium <code>PointPrimitiveCollection</code>), styled distinctly from cluster and sample-mode points (e.g., outlined ring rather than filled dot, distinct color). Owned by <code>zoomWatcher</code>’s search handler, not the cluster/sample-mode handlers. Lifecycle:</p>
<ul>
<li>Populated by <code>doSearch()</code> after results are computed. One pin per result, positioned at <code>(longitude, latitude, 0)</code>. Opt-in to picking (clicking a pin behaves like clicking a sample-mode point: <code>updateSampleCard()</code> + <code>pid</code> hash write).</li>
<li>Cleared by:
<ul>
<li>User clears the search input (or <code>?search=</code> is removed from URL).</li>
<li>User triggers a new search (overlay is replaced with new results).</li>
</ul></li>
<li>Shown in both globe cluster mode and point mode. The cluster layer remains accurate; the overlay is layered above as visual answer to “where did my search land geographically.”</li>
</ul>
<p><strong>Why (C) over (B).</strong></p>
<ul>
<li>Solves <a href="https://github.com/isamplesorg/isamplesorg.github.io/issues/163">#163 item 4</a> cleanly: zero results render zero pins (and the populated map clusters remain visibly <em>not</em> the search results, distinguishable by styling). Non-zero results show a coherent visual answer.</li>
<li>Preserves the “imperative globe; URL-canonical state” framing — cluster and facet behavior is unaffected, no reactive cascade.</li>
<li>Doesn’t conflate “search matched these samples” with “active filter” (which is what option A does); the user retains source/facet/view as independent orienting controls.</li>
</ul>
<p><strong>Costs of (C) we accept.</strong></p>
<ul>
<li>One additional Cesium primitive collection. The viewer cell at <code>:773</code> needs a <code>v.searchResultPoints = new Cesium.PointPrimitiveCollection()</code> alongside the existing <code>h3Points</code> and <code>samplePoints</code>.</li>
<li>One additional <code>data-pid</code> data path: the search-result pin click handler duplicates the sample-mode click handler. Acceptable; both paths are small.</li>
</ul>
</section>
<section id="implementation-rules-for-option-c" class="level3" data-number="1.6.4">
<h3 data-number="1.6.4" data-anchor-id="implementation-rules-for-option-c"><span class="header-section-number">1.6.4</span> Implementation rules for option (C)</h3>
<p>These are not negotiable defaults during implementation:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 60%">
<col style="width: 40%">
</colgroup>
<thead>
<tr class="header">
<th>concern</th>
<th>rule</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Pin count cap</strong></td>
<td>maximum <strong>50</strong> pins, matching the existing search result <code>LIMIT 50</code> (the <em>displayed</em> result set size). The full match set may exceed 50; the substrate query truncates to top-K before pin rendering. Pin count therefore equals <code>min(50, total_matches)</code>, never more, never fewer</td>
</tr>
<tr class="even">
<td><strong>Z-order</strong></td>
<td>search-result pins render <strong>above</strong> both H3 cluster points and sample-mode points. Implementation: add <code>searchResultPoints</code> to <code>scene.primitives</code> <em>after</em> <code>h3Points</code> and <code>samplePoints</code></td>
</tr>
<tr class="odd">
<td><strong>Pin styling</strong></td>
<td>hollow ring with bright outline (distinct from cluster filled-dot and sample-mode small filled-dot). Color follows the source palette (<code>SOURCE_COLORS</code>) so a glance still tells you which source matched. Pixel size larger than sample-mode pins (e.g., <code>8</code> vs <code>6</code>) so the overlay reads as primary</td>
</tr>
<tr class="even">
<td><strong>Hover label</strong></td>
<td>identical pattern to existing pointLabel handler — <code>meta.label \|\| meta.pid</code>, source badge color</td>
</tr>
<tr class="odd">
<td><strong>Click behavior</strong></td>
<td>identical to sample-mode click: <code>updateSampleCard()</code> + <code>pid</code> hash write. Single click handler can dispatch on <code>meta.type === 'searchResult'</code> vs <code>'sample'</code></td>
</tr>
<tr class="even">
<td><strong>Camera fit-to-bounds</strong></td>
<td>only fit-to-bounds when the result-set lat/lng extent <strong>&lt; 30° × 30°</strong>. Otherwise: fly to top-1 result at altitude <code>200000</code> (same as today’s first-result behavior). The 30° rule prevents a globally distributed result set from triggering a zoom-out to a near-globe view, which would be disorienting and wash out the cluster context</td>
</tr>
<tr class="odd">
<td><strong>Lifecycle</strong></td>
<td>populated immediately after results return; cleared on (a) search input cleared by user, (b) <code>?search=</code> removed from URL, (c) new search submitted (replaces the old overlay)</td>
</tr>
</tbody>
</table>
</section>
<section id="result-set-shape-acceptance-cases" class="level3" data-number="1.6.5">
<h3 data-number="1.6.5" data-anchor-id="result-set-shape-acceptance-cases"><span class="header-section-number">1.6.5</span> Result-set shape acceptance cases</h3>
<p>Implementation must visually verify the four shape cases:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 34%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>case</th>
<th>description</th>
<th>expected behavior</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>zero</strong></td>
<td><code>xyzzyqqqplugh</code></td>
<td>no pins; side-panel says “No results”; cluster layer + facets unaffected; camera not flown</td>
</tr>
<tr class="even">
<td><strong>one</strong></td>
<td>a <code>pid</code>-specific search that hits exactly one sample</td>
<td>one pin; fly-to-result at standard altitude; side panel shows the single result</td>
</tr>
<tr class="odd">
<td><strong>local-many</strong></td>
<td><code>pottery Cyprus</code> (results clustered in one region)</td>
<td>up to 50 pins, lat/lng extent &lt; 30°×30° → fit-to-bounds zoom</td>
</tr>
<tr class="even">
<td><strong>global-many</strong></td>
<td><code>basalt</code> (results spread across multiple continents)</td>
<td>up to 50 pins, extent ≥ 30°×30° → fly to top-1 at standard altitude; pins remain visible at multiple zoom levels via the cluster-overlay <code>scaleByDistance</code></td>
</tr>
</tbody>
</table>
</section>
<section id="state-inventory-addendum-for-c" class="level3" data-number="1.6.6">
<h3 data-number="1.6.6" data-anchor-id="state-inventory-addendum-for-c"><span class="header-section-number">1.6.6</span> State-inventory addendum for (C)</h3>
<p>The state contract grows a small amount:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 19%">
<col style="width: 17%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th>location</th>
<th>role</th>
<th>written by</th>
<th>read by</th>
<th>notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>viewer.searchResultPoints</code></td>
<td>Cesium <code>PointPrimitiveCollection</code> for search-result pins</td>
<td><code>zoomWatcher</code> (search handler)</td>
<td>mouse-move + click handlers</td>
<td>new collection; lifecycle tied to <code>?search=</code> non-empty</td>
</tr>
<tr class="even">
<td><code>viewer._searchResults</code> (Array)</td>
<td>array of result rows currently rendered as pins</td>
<td><code>zoomWatcher</code> (search handler)</td>
<td>future “fit-to-bounds” logic</td>
<td>optional cache; can be dropped if not needed</td>
</tr>
</tbody>
</table>
<p>URL/hash params are unchanged from (B). The DOM-as-state inventory is unchanged.</p>
<p><strong>Note for parallel investigation.</strong> A separate workstream (Codex, May 8) is auditing full-text-search status, indexing options, and speed. The (C) decision is intentionally orthogonal to the backend — <em>which UI surface displays the matches</em> is independent of <em>how the matches are computed</em>. If that investigation recommends switching the backend (e.g., from in-browser ILIKE → static-Parquet inverted index → hosted-search service), (C) is compatible with all of them.</p>
</section>
<section id="light-path-addendum-two-button-scope-selection-178-2026-05-08" class="level3" data-number="1.6.7">
<h3 data-number="1.6.7" data-anchor-id="light-path-addendum-two-button-scope-selection-178-2026-05-08"><span class="header-section-number">1.6.7</span> Light-path addendum: two-button scope selection (<a href="https://github.com/isamplesorg/isamplesorg.github.io/issues/178">#178</a>, 2026-05-08)</h3>
<p>Hana’s mockup (<a href="https://www.figma.com/design/Nqkuqh3Z4aqVh0nmwUAgKg/iSamples-Wireframe-1.0?node-id=213-394">Figma 213:394</a>) proposed a two-button search UI: “Search Selected Areas” (viewport-scoped) and “Search Entire World” (full-corpus). Implemented as a Light extension of (C), not a revisit of the A/B/C decision:</p>
<ul>
<li>“Search Entire World” runs the existing (C) full-corpus side-panel lookup with result-pin overlay. Behavior unchanged from the contract above. SQL shape: CTE over <code>sample_facets_v2</code> → top-50 → <code>LEFT JOIN</code> to <code>samples_map_lite</code> for display coords (samples without coords still appear; lat/lng are null).</li>
<li>“Search Selected Areas” runs the same text predicate but with a different SQL shape: <code>INNER JOIN</code> <code>samples_map_lite</code> inside the candidate selection, viewport <code>BETWEEN</code> predicate applied <strong>before</strong> <code>ORDER BY ... LIMIT 50</code>. This is critical — applying viewport after the global top-50 produces false zeroes (the global top-50 is concentrated in a few hot regions; a Sudan-area <code>pottery</code> query would return zero even though Sudan has plenty of pottery hits). Dateline-crossing is split into two longitude ranges.</li>
<li>URL state gains <code>?search_scope=area|world</code>; default <code>world</code>, omitted from URL when default. Hydrated on boot; written by <code>persistSearchScope()</code>.</li>
<li>Result-pin overlay still applies in both modes — pin coordinates reflect what was found, viewport-scope just narrows the candidate set.</li>
<li>Auto-fly to the first result is suppressed in area mode (the user is already at the area they care about; flying would zoom in and disorient).</li>
<li>Area mode requires coordinates by definition, so the <code>INNER JOIN</code> drops samples that have facets but no <code>samples_map_lite</code> row. World mode keeps them (via <code>LEFT JOIN</code>) since coord-less samples are still legitimate text matches.</li>
</ul>
<p>A future Heavy revisit may rethink (A) global-filter semantics if usage data shows users <em>expect</em> the map and facets to update with search. That decision is deferred until #170-#172 land.</p>
</section>
<section id="mockup-v1-addendum-in-map-overlay-sidebar-mirror-permanent-table-200-2026-05" class="level3" data-number="1.6.8">
<h3 data-number="1.6.8" data-anchor-id="mockup-v1-addendum-in-map-overlay-sidebar-mirror-permanent-table-200-2026-05"><span class="header-section-number">1.6.8</span> Mockup-v1 addendum: in-map overlay, sidebar mirror, permanent table (<a href="https://github.com/isamplesorg/isamplesorg.github.io/issues/200">#200</a>, 2026-05)</h3>
<p>A coordinated UI refactor aligning the explorer with Hana’s wireframe. Built as a single PR sequenced into independently revertable commits. All changes are UI-relocation / surface-additive; the data/query contract is unchanged from the (C) decision + #178 light path above.</p>
<p><strong>M-1A — Search controls relocated into an in-map overlay.</strong> The search input, the two scope buttons (Search Selected Areas / Search Entire World), help text, and <code>#searchResults</code> count moved from a top-of-page <code>.explorer-controls</code> block into <code>.map-search-overlay</code>, absolutely positioned over <code>#cesiumContainer</code> inside a new <code>.map-wrap</code> wrapper. All element IDs preserved so existing handlers in <code>zoomWatcher</code> and the <code>writeQueryState()</code> contract bind unchanged. Overlay positioning clears the Cesium toolbar column (<code>left: 50px</code>) and the base-layer picker dropdown wins z-stack (<code>z-index: 1100</code> vs overlay’s <code>1000</code>).</p>
<p><strong>M-1B — Sidebar open-text search input that mirrors the in-map one.</strong> A second input <code>#sampleSearchSidebar</code> lives at the top of <code>.side-panel</code>. Two-way <code>input</code>-event mirror keeps both inputs in lock-step as a single logical query term:</p>
<ul>
<li>Typing in <code>#sampleSearchSidebar</code> propagates to <code>#sampleSearch</code>.</li>
<li>Typing in <code>#sampleSearch</code> propagates to <code>#sampleSearchSidebar</code>.</li>
<li>Mirror handlers guard against feedback loops by comparing values before assignment; programmatic <code>.value =</code> does not fire <code>input</code>, so the comparison is sufficient (no debounce flag).</li>
<li><code>applyQueryToSearch()</code> hydrates <em>both</em> inputs from the <code>?search=</code> URL param.</li>
<li><code>writeQueryState()</code> still reads from <code>#sampleSearch</code> only — mirror parity makes the choice arbitrary.</li>
</ul>
<p><strong>Sidebar Enter = world scope (Option B).</strong> Enter on <code>#sampleSearchSidebar</code> always calls <code>doSearch('world')</code>, regardless of the in-map two-button scope choice. Rationale: typed-text-from-sidebar implies “find anywhere”; the in-map buttons remain the explicit way to constrain to current viewport. Both Enter handlers gate on <code>!e.isComposing &amp;&amp; e.keyCode !== 229</code> so IMEs that emit Enter to commit a candidate don’t submit on the pre-commit value.</p>
<p><strong>M-2 — Display-only color legend at bottom-center of the map.</strong> <code>.map-color-legend</code> is a static <code>aria-hidden="true"</code> swatch row with <code>pointer-events: none</code>. It mirrors the four-source palette from <code>assets/js/source-palette.js</code> and never affects filter state — the functional toggles remain in <code>#sourceFilter</code> in the sidebar. Sits above Cesium’s bottom-left credits via <code>bottom: 30px</code>.</p>
<p><strong>M-5 — Permanent samples table; Globe/Table toggle removed.</strong> The biggest delta to this contract:</p>
<ul>
<li><code>#globeViewBtn</code>, <code>#tableViewBtn</code>, <code>body.table-view-active</code>, <code>isTableViewActive()</code>, and the <code>?view=</code> URL param are all <strong>gone</strong>.</li>
<li>The samples table is always visible below the globe. Map height shrinks to <code>clamp(400px, 50vh, 540px)</code> (was 500/65vh/680) so the table fits below without a full-page-height feel.</li>
<li><code>tableView</code> cell initializes by calling <code>refreshTable()</code> unconditionally on boot.</li>
<li><code>writeQueryState()</code> does <code>params.delete('view')</code> to canonicalize legacy bookmarked <code>?view=table&amp;...</code> URLs. Caveat: only the next <code>writeQueryState()</code> call strips the param — hash-only writes via <code>buildHash(viewer)</code> (camera moves, sample/cluster click, Share) preserve <code>location.search</code> as-is, so <code>?view=</code> lingers until the user touches a filter, the search box, or anything else that flows through <code>writeQueryState()</code>.</li>
<li><strong>Table-row click = sample-mode globe click.</strong> Clicking a row in <code>.samples-table tbody tr[data-pid]</code> reuses the same async-selection ceremony as the search-row click handler (and the on-globe sample-point click), with one table-specific addition: the direct hash write. Preconditions before any work: bail if <code>e.target.tagName === 'A'</code> (let inline source-link clicks through), bail if the row has no resolvable sample / no lat-lng, bail if <code>typeof viewer === 'undefined'</code>. Once preconditions pass:
<ol type="1">
<li><code>const isStale = freshSelectionToken(viewer)</code> — bump BEFORE any await.</li>
<li><code>viewer._globeState.selectedPid</code> set; <code>selectedH3</code> cleared.</li>
<li><code>updateSampleCard({...})</code> populates the sidebar.</li>
<li><code>viewer.camera.flyTo({...})</code> at altitude <code>50000</code>.</li>
<li><strong>Table-specific:</strong> <code>history.replaceState(null, '', buildHash(viewer))</code> writes the <code>#pid</code> hash directly. The search-row and globe-point paths do not need this — they rely on <code>zoomWatcher</code>’s camera listener to fold selection into the hash. The table-row path can fire at very-early-boot before <code>zoomWatcher</code> is wired and while <code>_suppressHashWrite</code> is still <code>true</code>, so it writes the hash itself.</li>
<li>Repaint <code>.selected</code>: remove from any prior <code>tr.selected</code>, add to the clicked row — synchronously, before the async detail query.</li>
<li>Lazy-load <code>description</code> from <code>wide_url</code> with the pid SQL-escaped via <code>pid.replace(/'/g, "''")</code>; gated on <code>if (isStale()) return</code> before any DOM/state mutation. The error branch also stale-checks. A <code>rowsByPid: Map</code> cached at <code>refreshTable()</code> time gives O(1) per-PID lookup on click.</li>
</ol></li>
<li><strong>Asymmetric selection sync.</strong> Clicking a table row updates the globe + sidebar + URL. Clicking a globe point or a search-result row does NOT live-update the table’s <code>.selected</code> class — the table only repaints <code>.selected</code> on the next <code>renderTable()</code>. Treated as acceptable scope for v1; bidirectional highlight is a follow-up.</li>
</ul>
<p><strong>State surfaces added by mockup-v1.</strong> See the table additions in §1 (URL params: <code>search_scope</code>; legacy <code>view</code> struck), §3 (DOM-as-state: <code>tr.selected</code>, <code>data-pid</code> on table rows; <code>body.table-view-active</code> struck), and §5 (OJS cell graph: <code>tableView</code> no longer writes <code>view</code> to URL; <code>tableView</code> does write <code>#pid</code> to hash via <code>buildHash</code>).</p>
</section>
<section id="table-v2-addendum-server-side-pagination-218-2026-05" class="level3" data-number="1.6.9">
<h3 data-number="1.6.9" data-anchor-id="table-v2-addendum-server-side-pagination-218-2026-05"><span class="header-section-number">1.6.9</span> Table v2 addendum: server-side pagination (<a href="https://github.com/isamplesorg/isamplesorg.github.io/issues/218">#218</a>, 2026-05)</h3>
<p>Follow-up to the mockup-v1 PR. The samples table no longer fetches up to 25,000-100,000 rows up-front and paginates client-side. Each page is now its own DuckDB <code>LIMIT TABLE_PAGE_SIZE OFFSET page*size</code> query, plus one <code>COUNT(*)</code> query per filter change. Removes the <code>#maxSamples</code> input + <code>getTableMaxSamples()</code> / <code>clampTableMaxSamples()</code> helpers entirely.</p>
<p><strong>Determinism.</strong> <code>ORDER BY pid</code> plus <code>WHERE pid IS NOT NULL</code> on <strong>both</strong> the page query and the <code>COUNT(*)</code> query makes “Page N is the same N rows” actually true, and keeps the count consistent with what’s pageable. Defensive null filter even though <code>pid</code> is the canonical identifier and should never be null — ORDER BY a column that contains nulls is only deterministic by accident on a read-only parquet snapshot, and an unfiltered count could over-enable pagination past the last non-null page.</p>
<p><strong>Stale-while-loading.</strong> When filters change or the user pages, the existing rendered rows stay visible (dimmed to 60% opacity via <code>#tableContainer.is-loading .samples-table</code>) while the new page+count queries run in the DuckDB Web Worker. A CSS-only spinner appears in <code>#tableMeta</code>. <code>#tableContainer[aria-busy="true"]</code> exposes the state to screen readers. The pager-info text is cleared during load to avoid showing stale “Page 3 of 12 (200-300 of 1,200)” against an incoming filter set. <code>prefers-reduced-motion</code> is honored.</p>
<p><strong>Race protection.</strong> A <code>pageGen</code> integer is bumped on every refresh. Inner queries (<code>loadCount</code>, <code>loadPage</code>) compare <code>gen === pageGen</code> BEFORE mutating <code>pageRows</code>, <code>pageRowsByPid</code>, <code>totalRows</code>, or <code>currentPage</code>. <code>refreshAll</code> / <code>refreshPage</code> re-check the same gen before clearing the loading state, so a faster newer load can win the visible UI even if an older load resolves last.</p>
<p><strong>Error handling.</strong> <code>loadCount</code> and <code>loadPage</code> both return <code>true</code>/<code>false</code> to the orchestrator. Three distinct error surfaces:</p>
<ul>
<li><strong>Page load failed:</strong> meta shows the error, <code>lastPageFailed</code> flag flips on, and <code>renderTable()</code> swaps the table body for an explicit “Page query failed. Adjust filters or click Previous/Next to retry.” sentinel row (rather than leaving the old, now-inert rows visible with a cleared <code>pageRowsByPid</code>). Pager text is cleared.</li>
<li><strong>Count failed but page succeeded:</strong> rows render, but <code>totalRows</code> stays <code>null</code>. Pager text shows “Page N” without the total. The Next button is disabled while <code>totalRows == null</code> (so a user can’t click it into a no-op handler).</li>
<li><strong>Both failed:</strong> generic error meta; sentinel table state.</li>
</ul>
<p>This replaces the round-1 codex finding where the error meta was being overwritten by the success summary, and the round-2 finding where a failed page left old DOM visible but pageRowsByPid empty.</p>
<p><strong>Click handler unchanged.</strong> Table-row click uses <code>pageRowsByPid: Map</code> (renamed from <code>rowsByPid</code>) which is now scoped to the current page only — sufficient since only the visible page has clickable rows.</p>
<p><strong>Viewport coupling</strong> (PR #219, added shortly after table v2): both the page and count queries now include <code>viewerBboxSQL('latitude', 'longitude', 0.3)</code> which expands to <code>AND latitude BETWEEN &lt;s&gt; AND &lt;n&gt; AND &lt;lng-clause&gt;</code> (with dateline-crossing handling, including the post-padding wrap case where a non-wrapping rect spills past ±180 after the 30% expansion).</p>
<p><strong>Known pre-existing wrap bug NOT fixed in this PR.</strong> <code>loadViewportSamples()</code> in <code>zoomWatcher</code> (the point-mode sample loader) has its own padding logic that does <em>not</em> split the longitude predicate when the padded rectangle wraps the antimeridian — <code>bounds.east - bounds.west</code> is meaningless for a wrapping viewport, and the resulting single <code>BETWEEN</code> clause can return zero matches. This PR’s table queries now route through <code>viewerBboxSQL()</code> and split the wrapped predicate correctly, so the <strong>table is fine</strong> at the dateline; the bug is now only in the point-mode count (phase-msg “Samples in View”). At wrapping viewports the two surfaces will therefore diverge: table shows the correct row set, phase-msg can read zero or undercount. Scoped out as a follow-up because the user’s primary complaint (table=6M vs phase-msg=153 at Crete) is unrelated to the dateline. Right fix is to share the <code>viewerBboxSQL</code>-style normalization with point-mode. The shared <code>VIEWPORT_PAD_FACTOR</code> (0.3) is applied by the table query, the point-mode loader, and the cluster-mode <code>countInViewport()</code> call sites, so all three surfaces use the same padded bbox for their “in view” counts in the non-dateline, non-facet-filtered case. Caveats called out below: point mode still has the antimeridian padding bug (#220), cluster counts are H3-cell-granularity approximations, and cluster H3 loads don’t apply the material/context/object-type facet filters — so under those conditions the counts can still diverge independent of this PR. Issue #221 was three sources of divergence:</p>
<ol type="1">
<li><strong>Cache reuse (point mode).</strong> The point-mode loader cached a padded bbox + <code>cachedTotalCount</code> and short-circuited cache-hit pans (re-using the prior count) while the table re-queried the current padded bbox each time. Removed: both surfaces always re-fetch.</li>
<li><strong>Different trigger events (point mode).</strong> The table refreshed on every <code>viewer.camera.moveEnd</code>, but point-mode samples only refreshed through the debounced <code>camera.changed</code> handler (<code>percentageChanged = 0.1</code>), so small sub-10% pans refreshed the table without touching point-mode. Fixed: point-mode now also re-fetches on <code>moveEnd</code> (the <code>camera.changed</code> “already in point mode” branch is now a no-op).</li>
<li><strong>Unpadded cluster bbox (cluster mode, round 2).</strong> The cluster “Samples in View” stat called <code>countInViewport(getViewportBounds())</code> with the <strong>raw</strong> view rectangle, while the table queried the 30%-padded bbox — so the table consistently overcounted by the padding ring (e.g.&nbsp;at alt=302 km over Egypt: table=34,983 vs phase-msg=34,879). Fixed: the three <code>countInViewport</code> call sites now pass <code>paddedViewportBounds(VIEWPORT_PAD_FACTOR)</code>, sharing the same wrap-normalization helper that <code>viewerBboxSQL</code> uses.</li>
</ol>
<p><code>exitPointMode()</code> bumps <code>requestId</code> so any sample query still in flight when the user zooms out is invalidated before it can repaint stat boxes / phase-msg with stale point-mode numbers.</p>
<p>Residual cluster-mode divergence: even with matching bboxes, <code>countInViewport</code> filters H3 cells by their <em>center</em> and credits each cell’s full <code>sample_count</code>, while the table filters individual sample lat/lng — so at low H3 resolutions (res 4, alt &gt; 3 Mm) a small granularity-based gap remains. Inherent to cluster aggregation; not addressed here.</p>
<p>Note: this is <strong>viewport-count parity only</strong>. The pre-existing antimeridian wrap bug in point-mode’s own bbox padding (<code>latitude/longitude BETWEEN ...</code> doesn’t split the wrapped longitude predicate) still causes the phase-msg to undercount near the dateline. That’s tracked separately (issue #220).</p>
<p><code>doSearch('area')</code> calls the same helper without a padFactor (= undefined, no padding), since search has always been documented as “samples within the current map view.”</p>
<p>The table re-fires on <code>viewer.camera.moveEnd</code>, so panning/zooming the globe re-scopes the table. <strong>Null-bbox handling</strong>: if the camera can’t produce a view rectangle (off-globe; rare), <code>viewerBboxSQL()</code> returns <code>null</code>. The table treats this as a status state (“No globe area in view; pan or zoom the globe to see samples.”) rather than falling back to a no-bbox query — that’s the bug shape PR #219 was filed against. Area search keeps its existing world fallback.</p>
<p><strong>Boot ordering</strong>: the viewer cell’s <code>once()</code> postRender handler now sets <code>viewer._initialCameraApplied = true</code> after <code>setView</code>. The table defers its first refresh until either (a) the flag is true at cell-run time, or (b) the <code>camera.moveEnd</code> listener fires (which it will, once <code>setView</code> lands). This avoids the brief flash of world-view rows at boot when the URL hash specifies a deep-zoom camera.</p>
<hr>
</section>
</section>
<section id="facet-count-contract" class="level2" data-number="1.7">
<h2 data-number="1.7" data-anchor-id="facet-count-contract"><span class="header-section-number">1.7</span> 7. Facet-count contract</h2>
<p>The cross-filter rule (codified by Codex in #158, restated here):</p>
<table class="caption-top table">
<colgroup>
<col style="width: 26%">
<col style="width: 47%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th>dimension</th>
<th>counts respect it?</th>
<th>rationale</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>other facet selections</td>
<td><strong>YES</strong></td>
<td>counts answer “if I add this value, how many samples would match all OTHER active filters plus this one”; that’s the drill-out signal users want</td>
</tr>
<tr class="even">
<td>viewport (camera bounds)</td>
<td><strong>NO</strong></td>
<td>counts are global. Viewport-scoped counts would couple facet UI to camera state, contradict the “facets describe the dataset” reading, and require re-querying on every camera change</td>
</tr>
<tr class="odd">
<td><code>?search=</code> text query</td>
<td><strong>NO</strong></td>
<td>option (C); search renders a side panel + result-pin overlay, but does not alter facet counts</td>
</tr>
<tr class="even">
<td><del>view mode (globe vs table)</del></td>
<td><em>moot — mockup-v1 (#200) removed the Globe/Table toggle; both surfaces are permanent</em></td>
<td>—</td>
</tr>
</tbody>
</table>
<p>Exposed via <code>applyFacetCounts(facetKey, countsMap)</code> (<code>:551-567</code>):</p>
<ul>
<li><code>countsMap = null</code> ⇒ render the baseline counts from <code>viewer._baselineCounts</code>.</li>
<li><code>countsMap = Map&lt;value, count&gt;</code> ⇒ render the cross-filtered counts; missing keys render as <code>0</code> (and pick up the <code>.zero</code> class).</li>
</ul>
<p>The “single active dim” fast path (<code>:1548-1584</code>) reads from a pre-aggregated <code>cross_filter_url</code> parquet for instant response when exactly one facet value is selected; the general path (<code>:1586-1604</code>) issues four parallel <code>GROUP BY</code> queries against <code>facets_url</code>, one per dimension, each excluding its own active values from the WHERE.</p>
<hr>
</section>
<section id="out-of-scope" class="level2" data-number="1.8">
<h2 data-number="1.8" data-anchor-id="out-of-scope"><span class="header-section-number">1.8</span> 8. Out of scope</h2>
<ul>
<li>Refactoring into modules (<code>urlState</code>, <code>globeView</code>, <code>facetCounts</code>, <code>tableView</code>, <code>sampleCard</code>, <code>search</code>). Once this contract is stable, the modular rewrite is a follow-up — not a prerequisite.</li>
<li>Pure-OJS-reactive vs pure-imperative migration. We commit to imperative + URL-canonical here; the mechanical rewrite is separate.</li>
<li>UX/copy items 1, 2, 3, 5, 6 from #163. They unblock against this contract but don’t belong in it.</li>
<li>Backend changes to the search query (FTS index, server-side service). See the parallel Codex investigation.</li>
</ul>
<hr>
</section>
<section id="acceptance-signals" class="level2" data-number="1.9">
<h2 data-number="1.9" data-anchor-id="acceptance-signals"><span class="header-section-number">1.9</span> 9. Acceptance signals</h2>
<ul>
<li>✅ Inventory tables populated from current <code>explorer.qmd</code>.</li>
<li>✅ Search-semantics decision recorded with rationale (option C, side-panel + result-pin overlay).</li>
<li>✅ Facet-count contract restated.</li>
<li>⏭ #163 items can now be re-scoped against this doc:
<ul>
<li><strong>#163 item 4</strong> (zero search results + populated map looks broken) is resolved by option C, not by side-panel copy alone. Implementation must verify all four result-set shape cases (zero, one, local-many, global-many) per the table in §6.</li>
<li><strong>#163 item 6</strong> (page in URL) gets a clear contract slot to plug into (a <code>page</code> query param participating in the same <code>writeQueryState</code>/ hydration cycle as <code>view</code>).</li>
<li>The remaining items (1, 2, 3, 5, 7) are state-preserving UI fixes that don’t perturb this contract.</li>
</ul></li>
</ul>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© Copyright 2020-2026, iSamples Project. Based on work under National Science Foundation (NSF) Grant Numbers <a href="https://nsf.gov/awardsearch/showAward?AWD_ID=2004839">2004839</a>, <a href="https://nsf.gov/awardsearch/showAward?AWD_ID=2004562">2004562</a>, <a href="https://nsf.gov/awardsearch/showAward?AWD_ID=2004642">2004642</a>, and <a href="https://nsf.gov/awardsearch/showAward?AWD_ID=2004815">2004815</a>.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/isamplesorg/isamplesorg.github.io/edit/main/EXPLORER_STATE.md" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/isamplesorg/isamplesorg.github.io/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Opinions, findings, and conclusions or recommendations expressed in this material are those of the authors and do not necessarily reflect the views of the <a href="https://nsf.gov/">NSF</a>.</p>
</div>
  </div>
</footer>




</body></html>