@startuml
skinparam monochrome true
partition iSB {
    :Source;
    -> load;
    :isb_thing
    [postgres];
    -> transform;
    :isb_index
    [solr];
    -[dashed]-> synchronize;
}
partition iSC {
    :isc_thing
    [postgres];
    :isc_index
    [solr];
}


@enduml