// Unit tests for assets/js/search_substrate.js (#171 Phase A).
// FNV-1a parity values come from tools/build_search_index.py (fixture
// generated by the Python implementation — same pattern as the tokenizer
// regression set).
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import {
    fnv1a32, planQuery, bm25Contribution, combineAndRank,
    QUERY_STOPWORDS, FIELD_WEIGHTS, BM25_K1, BM25_B,
} from '../../assets/js/search_substrate.js';

const here = dirname(fileURLToPath(import.meta.url));
const FNV = JSON.parse(readFileSync(join(here, '..', 'search_fnv1a_regression.json'), 'utf8'));

test('fnv1a32 parity with Python (20-entry fixture incl. CJK/Cyrillic/Greek)', () => {
    for (const { input, fnv1a32: expected } of FNV) {
        assert.equal(fnv1a32(input), expected, `fnv1a32(${JSON.stringify(input)})`);
    }
});

const MANIFEST = {
    shardCount: 256,
    hotTokens: { material: { key: 'deadbeef', sub_files: 3 } },
};

test('planQuery: stopword policy + duplicate-term dedup', () => {
    const p1 = planQuery('pottery from Cyprus', MANIFEST);
    assert.deepEqual(p1.tokens, ['pottery', 'cyprus']);   // 'from' dropped
    const p2 = planQuery('pottery pottery cyprus', MANIFEST);
    assert.deepEqual(p2.tokens, ['pottery', 'cyprus']);   // dupes collapse
    // #172 hard-fail precondition: both plans fetch identical files.
    assert.deepEqual(p1.files, p2.files);
});

test('planQuery: all-stopword input → controlled empty, no fetches', () => {
    const p = planQuery('a the of', MANIFEST);
    assert.equal(p.allStopwords, true);
    assert.equal(p.empty, false);
    assert.deepEqual(p.files, []);
});

test('planQuery: empty/whitespace input', () => {
    const p = planQuery('   ', MANIFEST);
    assert.equal(p.empty, true);
    assert.equal(p.allStopwords, false);
});

test('planQuery: base-shard path uses fnv1a32 % shardCount, zero-padded', () => {
    const p = planQuery('pottery', MANIFEST);
    const shard = fnv1a32('pottery') % 256;
    assert.deepEqual(p.files, [`shard_${String(shard).padStart(3, '0')}.parquet`]);
});

test('planQuery: hot token resolves to its sub-file set', () => {
    const p = planQuery('material', MANIFEST);
    assert.deepEqual(p.files, [
        'hot/deadbeef_p0.parquet', 'hot/deadbeef_p1.parquet', 'hot/deadbeef_p2.parquet',
    ]);
});

test('planQuery: shared shard between tokens is fetched once', () => {
    // Construct two tokens that collide mod 2.
    const m = { shardCount: 1, hotTokens: {} };
    const p = planQuery('pottery basalt', m);
    assert.deepEqual(p.files, ['shard_000.parquet']);
    assert.equal(p.filesByToken.get('pottery')[0], 'shard_000.parquet');
});

test('bm25Contribution: hand-computed value', () => {
    // df=10 of 1000 docs, tf=2, doc_len=4, avg=8, field weight 3.0
    const row = { field: 'sample.label', tf: 2, doc_len: 4, df: 10 };
    const stats = { totalDocs: 1000, avgDocLen: 8 };
    const idf = Math.log((1000 - 10 + 0.5) / (10 + 0.5) + 1);
    const norm = (2 * 2.2) / (2 + 1.2 * (1 - 0.75 + 0.75 * 4 / 8));
    assert.ok(Math.abs(bm25Contribution(row, stats) - 3.0 * idf * norm) < 1e-12);
});

test('bm25Contribution: rarer token scores higher, heavier field scores higher', () => {
    const stats = { totalDocs: 1000, avgDocLen: 8 };
    const base = { field: 'sample.description', tf: 1, doc_len: 8 };
    const rare = bm25Contribution({ ...base, df: 2 }, stats);
    const common = bm25Contribution({ ...base, df: 500 }, stats);
    assert.ok(rare > common);
    const label = bm25Contribution({ ...base, df: 10, field: 'sample.label' }, stats);
    const desc = bm25Contribution({ ...base, df: 10 }, stats);
    assert.ok(Math.abs(label / desc - 3.0) < 1e-9);  // weight ratio 3.0 : 1.0
});

test('combineAndRank: AND semantics + score summation + stable ties', () => {
    const stats = { totalDocs: 1000, avgDocLen: 8 };
    const row = (pid, field, df) => ({ pid, field, tf: 1, doc_len: 8, df });
    const postings = new Map([
        ['pottery', [row('p1', 'sample.label', 10), row('p2', 'sample.label', 10),
                     row('p3', 'concept.label', 10)]],
        ['cyprus', [row('p1', 'sample.description', 20), row('p3', 'sample.place_name', 20)]],
    ]);
    const out = combineAndRank(postings, stats);
    // p2 matched only 'pottery' → excluded (AND).
    assert.deepEqual(out.map(r => r.pid).sort(), ['p1', 'p3']);
    // p1: label(3.0) + description(1.0); p3: concept(2.5) + place(2.0) → p3 wins.
    assert.equal(out[0].pid, 'p3');
    // Ties break by pid ascending.
    const tied = combineAndRank(new Map([
        ['x', [row('b', 'sample.label', 10), row('a', 'sample.label', 10)]],
    ]), stats);
    assert.deepEqual(tied.map(r => r.pid), ['a', 'b']);
});

test('combineAndRank: top-K cap', () => {
    const stats = { totalDocs: 1000, avgDocLen: 8 };
    const rows = Array.from({ length: 80 }, (_, i) =>
        ({ pid: `p${String(i).padStart(2, '0')}`, field: 'sample.label',
           tf: 1, doc_len: 8, df: 10 }));
    const out = combineAndRank(new Map([['t', rows]]), stats);
    assert.equal(out.length, 50);
});

test('constants match the contract', () => {
    assert.equal(BM25_K1, 1.2);
    assert.equal(BM25_B, 0.75);
    assert.deepEqual(FIELD_WEIGHTS['sample.label'], 3.0);
    assert.ok(QUERY_STOPWORDS.has('from') && !QUERY_STOPWORDS.has('pottery'));
});
