// Unit tests for assets/js/search_substrate.js (#171).
// FNV-1a parity values come from tools/build_search_index.py (fixture
// generated by the Python implementation — same pattern as the tokenizer
// regression set). The manifest shapes mirror hot_tokens.json's two-tier
// schema (fetchable vs common terms, contract §6).
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import {
    fnv1a32, planQuery, bm25Contribution, combineAndRank,
    QUERY_STOPWORDS, FIELD_WEIGHTS, BM25_K1, BM25_B,
} from '../../assets/js/search_substrate.js';

const here = dirname(fileURLToPath(import.meta.url));
const FNV = JSON.parse(readFileSync(join(here, '..', 'search_fnv1a_regression.json'), 'utf8'));

test('fnv1a32 parity with Python (fixture incl. CJK/Cyrillic/Greek)', () => {
    for (const { input, fnv1a32: expected } of FNV) {
        assert.equal(fnv1a32(input), expected, `fnv1a32(${JSON.stringify(input)})`);
    }
});

// Two-tier manifest: 'material' is a true common term (non-fetchable);
// 'island' is storage-hot but fetchable (joins the AND normally).
const MANIFEST = {
    shardCount: 256,
    hotTokens: {
        material: { key: 'deadbeef', sub_files: 10, postings: 5_000_000,
                    total_bytes: 50_000_000, fetchable: false },
        island: { key: 'cafe0001', sub_files: 2, postings: 82_000,
                  total_bytes: 2_500_000, fetchable: true },
    },
};

test('planQuery: stopword policy + duplicate-term dedup', () => {
    const p1 = planQuery('pottery from Cyprus', MANIFEST);
    assert.equal(p1.mode, 'normal');
    assert.deepEqual(p1.tokens, ['pottery', 'cyprus']);   // 'from' dropped
    const p2 = planQuery('pottery pottery cyprus', MANIFEST);
    assert.deepEqual(p2.tokens, ['pottery', 'cyprus']);   // dupes collapse
    // #172 hard-fail precondition: both plans fetch identical files.
    assert.deepEqual(p1.files, p2.files);
});

test('planQuery: all-stopword input → controlled empty, no fetches', () => {
    const p = planQuery('a the of', MANIFEST);
    assert.equal(p.mode, 'allStopwords');
    assert.deepEqual(p.files, []);
});

test('planQuery: empty/whitespace input', () => {
    assert.equal(planQuery('   ', MANIFEST).mode, 'empty');
});

test('planQuery: base-shard path uses fnv1a32 % shardCount, zero-padded', () => {
    const p = planQuery('pottery', MANIFEST);
    const shard = fnv1a32('pottery') % 256;
    assert.deepEqual(p.files, [`shard_${String(shard).padStart(3, '0')}.parquet`]);
});

test('planQuery two-tier: common term dropped WITH disclosure when selective terms exist', () => {
    const p = planQuery('material basalt', MANIFEST);
    assert.equal(p.mode, 'normal');
    assert.deepEqual(p.tokens, ['basalt']);          // AND excludes 'material'
    assert.deepEqual(p.ignoredCommon, ['material']); // UI must disclose this
    assert.ok(!p.files.some(f => f.startsWith('hot/')));  // no hot bytes fetched
});

test('planQuery two-tier: fetchable hot joins the AND via its sub-files', () => {
    const p = planQuery('island basalt', MANIFEST);
    assert.equal(p.mode, 'normal');
    assert.deepEqual(p.tokens, ['island', 'basalt']);
    assert.deepEqual(p.ignoredCommon, []);
    assert.deepEqual(p.filesByToken.get('island'),
        ['hot/cafe0001_p0.parquet', 'hot/cafe0001_p1.parquet']);
});

test('planQuery two-tier: all-common query → topk mode, single sidecar file', () => {
    const p = planQuery('material', MANIFEST);
    assert.equal(p.mode, 'topk');
    assert.deepEqual(p.tokens, ['material']);
    assert.deepEqual(p.files, ['hot_topk.parquet']);
});

test('planQuery: expectedBytes = base shard sizes + fetchable-hot totals', () => {
    const potteryShard = `shard_${String(fnv1a32('pottery') % 256).padStart(3, '0')}.parquet`;
    const basaltShard = `shard_${String(fnv1a32('basalt') % 256).padStart(3, '0')}.parquet`;
    const sizes = { [potteryShard]: 3_000_000, [basaltShard]: 2_000_000 };
    const p = planQuery('island pottery basalt material', MANIFEST, sizes);
    // island (fetchable hot, 2.5MB) + pottery shard (3MB) + basalt shard (2MB);
    // 'material' is dropped (common) and costs nothing.
    assert.equal(p.expectedBytes, 2_500_000 + 3_000_000 + 2_000_000);
    assert.deepEqual(p.ignoredCommon, ['material']);
});

test('planQuery: shared shard between tokens is fetched once', () => {
    const m = { shardCount: 1, hotTokens: {} };
    const p = planQuery('pottery basalt', m, { 'shard_000.parquet': 1000 });
    assert.deepEqual(p.files, ['shard_000.parquet']);
    assert.equal(p.expectedBytes, 1000);   // counted once, not twice
});

const STATS = {
    totalDocs: 1000,
    avgDocLenByField: {
        'sample.label': 8, 'sample.description': 40,
        'sample.place_name': 8, 'concept.label': 8,
    },
};

test('bm25Contribution: hand-computed value (per-field avg doc len)', () => {
    const row = { field: 'sample.label', tf: 2, doc_len: 4, df: 10 };
    const idf = Math.log((1000 - 10 + 0.5) / (10 + 0.5) + 1);
    const norm = (2 * 2.2) / (2 + 1.2 * (1 - 0.75 + 0.75 * 4 / 8));
    assert.ok(Math.abs(bm25Contribution(row, STATS) - 3.0 * idf * norm) < 1e-12);
});

test('bm25Contribution: rarer token > common; field weights scale', () => {
    const base = { field: 'sample.description', tf: 1, doc_len: 40 };
    const rare = bm25Contribution({ ...base, df: 2 }, STATS);
    const common = bm25Contribution({ ...base, df: 500 }, STATS);
    assert.ok(rare > common);
    const label = bm25Contribution({ field: 'sample.label', tf: 1, doc_len: 8, df: 10 }, STATS);
    const desc = bm25Contribution({ field: 'sample.description', tf: 1, doc_len: 40, df: 10 }, STATS);
    // both rows sit exactly at their field's average length → norm equal;
    // ratio is purely the field-weight ratio 3.0 : 1.0
    assert.ok(Math.abs(label / desc - 3.0) < 1e-9);
});

test('combineAndRank: AND semantics + per-pid summation + stable ties', () => {
    const row = (pid, field, df) => ({ pid, field, tf: 1, doc_len: 8, df });
    const postings = new Map([
        ['pottery', [row('p1', 'sample.label', 10), row('p2', 'sample.label', 10),
                     row('p3', 'concept.label', 10)]],
        ['cyprus', [row('p1', 'sample.place_name', 20), row('p3', 'sample.place_name', 20)]],
    ]);
    const out = combineAndRank(postings, STATS);
    assert.deepEqual(out.map(r => r.pid).sort(), ['p1', 'p3']);  // p2 fails AND
    // p1: label(3.0)+place(2.0); p3: concept(2.5)+place(2.0) → p1 wins
    assert.equal(out[0].pid, 'p1');
    const tied = combineAndRank(new Map([
        ['x', [row('b', 'sample.label', 10), row('a', 'sample.label', 10)]],
    ]), STATS);
    assert.deepEqual(tied.map(r => r.pid), ['a', 'b']);
});

test('combineAndRank: top-K cap', () => {
    const rows = Array.from({ length: 80 }, (_, i) =>
        ({ pid: `p${String(i).padStart(2, '0')}`, field: 'sample.label',
           tf: 1, doc_len: 8, df: 10 }));
    const out = combineAndRank(new Map([['t', rows]]), STATS);
    assert.equal(out.length, 50);
});

test('constants match the contract', () => {
    assert.equal(BM25_K1, 1.2);
    assert.equal(BM25_B, 0.75);
    assert.deepEqual(FIELD_WEIGHTS['sample.label'], 3.0);
    assert.ok(QUERY_STOPWORDS.has('from') && !QUERY_STOPWORDS.has('pottery'));
});
